services:
  data-server:
    image: ${ECR_REGISTRY_URL}:latest
    container_name: ${DATA_SERVER_CONTAINER_NAME}
    ports:
      - ${DATA_SERVER_PORT}
    restart: always
    env_file:
      - ./.env